version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    container_name: frontend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: backend